apiapp/urls.py
from django.urls import path
from apiapp import views
app_name = 'api_app'
urlpatterns = [
    path('product/<product_slug>/', views.ProductApiView.as_view(), name='product'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminpanel/', include('adminpanelapp.urls')),
    path('', include('ecomapp.urls')),
    path('product/', include('productapp.urls')),
    path('purchase/', include('purchaseapp.urls')),
    path('account/', include('userapp.urls')),
    path('api/', include('apiapp.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomapp/urls.py
from django.urls import path
from ecomapp import views

app_name = 'ecom_app'

urlpatterns = [
    path('', views.indexView, name='index'),
    path('all/<category>/', views.pageView, name='all'),
    path('filter/', views.filterView, name='filter'),
]

productapp/urls.py
from django.urls import path
from productapp import views

app_name = 'product_details_app'

urlpatterns = [
    path('<product_slug>/', views.productDetailsView, name='product'),
    path('add_to_wishlist/<product_slug>/', views.addToWishListView, name='add_to_wishlist'),
    path('remove_from_wishlist/<id>/', views.removeFromWishListView, name='remove_from_wishlist'),

]

purchaseapp/urls.py
from django.urls import path
from purchaseapp import views

app_name = 'purchase_app'

urlpatterns = [
    path('add/<product_slug>/', views.addToCartView, name='add_to_cart'),
    path('plus/<product_slug>/', views.increaseCartView, name='plus_to_cart'),
    path('minus/<product_slug>/', views.decreaseCartView, name='minus_to_cart'),
    path('remove/<cart_id>/', views.deleteCartView, name='remove_from_cart'),
]

userapp/urls.py
from django.urls import path
from userapp import views
app_name = 'profile_app'

urlpatterns = [
    path('', views.profileView, name='profile'),
    path('orders/', views.historyView, name='order-history'),
    path('logout/', views.logoutView, name='logout'),
    path('login/', views.loginView, name='login'),
    path('signup/', views.registrationView, name='signup'),
    path('edit-info/', views.editProfileView, name='edit-profile'),
    path('change-password/', views.changePasswordView, name='change-password'),
    path('edit-billing-address/', views.editBillingAddressView, name='edit-billing-address'),
    path('edit-shipping-address/', views.editShippingAddressView, name='edit-shipping-address'),

    path('wishlist/', views.wishlistView, name='wish-list'),
    path('cart/', views.cartView, name='cart'),
]

templates/home/cart.html
{% extends 'home/base.html' %}
{% load static %}
{% block style_block %}

{% endblock %}
{% block body_block %}
    <div class="flex flex-col lg:flex-row gap-4">
        <div class="w-full lg:w-3/5">
            <div class="flex justify-between items-center border-b-2 pb-1">
                <h2 class="text-xl font-semibold">Shopping Cart</h2>
                <h2 class="text-xl">{{ carts.count }} Items</h2>
            </div>
            <div class="flex justify-center mt-1">
                <h2 class="w-1/5 text-center font-bold">Product Details</h2>
                <h2 class="w-1/5 text-center font-bold">Quantity</h2>
                <h2 class="w-1/5 text-center font-bold">Price</h2>
                <h2 class="w-1/5 text-center font-bold">Total</h2>
                <h2 class="w-1/5 text-center font-bold">Remove</h2>
            </div>
            {% for cart in carts %}
                <div class="flex justify-center mt-2 items-center border-b pb-1">
                    <div class="flex justify-center items-center w-1/5 text-center">
                        <img src="{{ cart.product.image.url }}" alt="{{ cart.product.product_name }}" class="w-1/2">
                        <h2 class="">{{ cart.product.product_name }}</h2>
                    </div>
                    <div class="flex justify-center items-center gap-1 w-1/5 text-center">
                        <a href="{% url 'purchase_app:minus_to_cart' product_slug=cart.product.product_slug %}"
                           class="bg-yellow-400 px-2 py-1 font-bold rounded-full" type="submit">-</a>
                        <h2 class="font-semibold">{{ cart.quantity }}</h2>
                        <a href="{% url 'purchase_app:plus_to_cart' product_slug=cart.product.product_slug %}"
                           class="bg-yellow-400 px-2 py-1 font-bold rounded-full" type="submit">+</a>
                    </div>
                    <h2 class="w-1/5 text-center">{{ cart.product.product_new_price }}</h2>
                    <h2 class="w-1/5 text-center">{{ cart.get_total }}</h2>
                    <div class="w-1/5 text-center"><a href="{% url 'purchase_app:remove_from_cart' cart_id=cart.id %}"
                                              class="bg-red-400 hover:bg-red-500 focus:bg-red-500 focus:outline-none text-white px-2 py-1 rounded"
                                              data-tootik="Remove From Cart"><i class="fal fa-trash"></i></a></div>

                </div>
            {% endfor %}

        </div>
        <div class="w-full lg:w-2/5">
            <div class=" sticky top-20">
                <h2 class="text-xl font-semibold border-b-2 pb-1">Order Summery</h2>
                <div class="flex justify-between px-8 mt-4">
                    <h2 class="font-semibold">Total:</h2>
                    <span class="">{{ order.get_totals }}</span>
                </div>
                <div class="flex justify-between px-8 mt-4">
                    <h2 class="font-semibold">Discount:</h2>
                    <span class="">10</span>
                </div>
                <div class="flex justify-between px-8 mt-4">
                    <h2 class="font-semibold">Grand Total:</h2>
                    <span class="">4990</span>
                </div>
                <div class="px-8 my-10">
                    <form action="" class="flex flex-col gap-2" method="POST">
                        <label class="" for="coupon">Coupon:</label>
                        <input type="text" class="border px-4 py-3 focus:outline-none" placeholder="Coupon" id="coupon"
                               name="coupon">
                        {% csrf_token %}
                        <button class="bg-yellow-400 px-4 py-3 rounded" type="submit">Add Coupon</button>
                    </form>
                </div>
                <div class="flex flex-col md:flex-row justify-between gap-2 px-8 mt-4">
                    <a href="{% url 'ecom_app:index' %}" class="bg-gray-800 text-white px-4 py-3 w-full text-center rounded">Continue Shopping</a>
                    <a href="" class="bg-yellow-400 px-4 py-3 w-full text-center rounded">Checkout</a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block script_block %}

{% endblock %}

templates/home/edit-info.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% block style_block %}

{% endblock %}

{% block body_block %}
    <div class="flex flex-col lg:flex-row gap-4">
        <div class="w-full lg:w-1/5">
            {% include 'home/profile-left-menu.html' %}
        </div>
        <div class="flex flex-col lg:flex-row gap-4 lg:w-4/5 w-full">
            <form action="" class="" method="POST" enctype="multipart/form-data">
                {{ form|crispy }}
                {% csrf_token %}
                <button type="submit" class="bg-yellow-400 hpver:bg-yellow-500 focus:bg-yellow-500 px-3 py-2 rounded-md">Edit</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/home/login.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% block style_block %}

{% endblock %}

{% block body_block %}

    <div class="p-10 border lg:mx-40">
        <div class="flex flex-col lg:flex-row text-center md:text-left pb-2 items-center justify-between">
            <h2 class="text-xl">Welcome, Please Login Here.</h2>
            <p class="">New Member? <a href="{% url 'account_signup' %}" class="text-blue-500">Register</a> Here.</p>
        </div>
        <div class="p-4">
            <form action="" class="flex flex-col md:flex-row items-center gap-8" method="POST">


                <div class="w-full md:w-1/2">
                    {{ form|crispy }}
                    <a href="{% url 'account_reset_password' %}" class="text-blue-500 text-xs py-2">Forget Password?</a>
                    {% csrf_token %}
                </div>

                <div class="w-full md:w-1/2 flex flex-col gap-4 text-center">
                    <button type="submit"
                            class="bg-yellow-400 transition duration-300 hover:bg-yellow-500 focus:bg-yellow-500 text-white p-3 w-full">
                        Login
                    </button>
                    {% providers_media_js %}
                    <a href="{% provider_login_url "facebook" method="js_sdk" %}"
                       class="bg-blue-400 transition duration-300 hover:bg-blue-500 focus:bg-blue-500 text-white p-3 w-full">Facebook</a>
                    <a href="{% provider_login_url "google" %}"
                       class="bg-red-400 transition duration-300 hover:bg-red-500 focus:bg-red-500 text-white p-3 w-full">Google</a>
                </div>

            </form>
        </div>
    </div>
{% endblock %}

templates/home/product-details.html
{% extends 'home/base.html' %}
{% load static %}
{% load my_filter %}
{% load crispy_forms_tags %}
{% block style_block %}
    <style>
        .star-widget label {

            float: right;
            transition: all 0.2s ease;
        }

        input:not(:checked) ~ label:hover,
        input:not(:checked) ~ label:hover ~ label {
            color: #fbbf24;
        }

        input#rate_five:checked ~ label {
            color: #fbbf24;
        }

        input:checked ~ label {
            color: #fbbf24;
        }
    </style>
{% endblock %}
{% block body_block %}
    <div class="flex gap-4 flex-col md:flex-row">
        <div class="product-image exzoom w-full md:w-1/2 lg:w-2/5" id="exzoom">
            <!-- Images -->
            <div class="exzoom_img_box">
                <ul class='exzoom_img_ul'>
                    {% for image in product.image_product.all %}
                        <li><img src="{{ image.product_image.url }}"/></li>
                    {% endfor %}
                </ul>
            </div>
            <!-- <a href="https://www.jqueryscript.net/tags.php?/Thumbnail/">Thumbnail</a> Nav-->
            <div class="exzoom_nav"></div>
            <!-- Nav Buttons -->
            <p class="exzoom_btn">
                <a href="javascript:void(0);" class="exzoom_prev_btn"> < </a>
                <a href="javascript:void(0);" class="exzoom_next_btn"> > </a>
            </p>
        </div>
        <div class="product-basic border rounded-md p-4 w-full md:w-1/2 lg:w-2/5">
            <h2 class="font-bold text-2xl">{{ product.product_name }}</h2>
            <div class="flex items-center gap-2 pt-3 text-yellow-400">
                {% for star in product.avg_rating|times %}
                    <i class="fa fa-star"></i>
                {% endfor %}
                {% for star in product.avg_rating|sub %}
                    <i class="fal fa-star"></i>
                {% endfor %}
                <h2 class="text-black text-lg">Total Ratings: {{ product.total_rating_count }}</h2>
            </div>
            <h2 class="text-md font-bold pt-3">Brand: <span class="text-blue-400 font-normal"><a
                    href="{% url 'ecom_app:all' category=product.company_name|lower|replacespace %}">{{ product.company_name }}</a></span>
            </h2>
            <h2 class="text-md font-bold pt-3">Availability:
                {% if product.product_quantity > 0 %}
                    <span class="text-yellow-600 font-normal">In Stock</span>
                {% else %}
                    <span class="text-red-600 font-normal">In Stock</span>
                {% endif %}

            </h2>
            <div class="py-3 flex items-center gap-4">
                <span class="text-3xl text-red-600">৳{{ product.product_new_price }}</span>
                <span class="text-3xl text-red-300 line-through">৳{{ product.product_price }}</span>
                <span class="bg-yellow-400 p-3 text-white">%{{ product.product_discount }}</span>
            </div>
            <hr>

            <h2 class="text-md font-bold text-xl pt-3">Options:</h2>
            {% if product.product_sizes.count > 0 %}
                <h2 class="text-md font-bold pt-3">Size:
                    <select name="size" id="size" class="border px-2 py-1">
                        {% for product_size in product.product_sizes.all %}
                            <option value="{{ product_size }}">{{ product_size }}</option>
                        {% endfor %}
                    </select>
                </h2>
            {% endif %}


            {% if product.product_colors.count > 0 %}
                <h2 class="text-md font-bold pt-3">Color:
                    <select name="color" id="color" class="border px-2 py-1">
                        {% for product_color in product.product_colors.all %}
                            <option value="{{ product_color }}">{{ product_color }}</option>
                        {% endfor %}
                    </select>
                </h2>
            {% endif %}

            <h2 class="text-md font-bold pt-3">Quantity:
                <input type="number" min="1" class="border px-2 py-1" value="1">
            </h2>
            <div class="flex pt-3 gap-4 flex-col xl:flex-row text-center">
                <a href="{% url 'product_details_app:add_to_wishlist' product_slug=product.product_slug %}"
                   class="py-3 px-4 bg-yellow-400 rounded text-white flex gap-2 items-center justify-center w-full"
                   data-tootik="Add to Wishlist"><i class="fa fa-heart"></i><span class="">Add to Wishlish</span></a>
                <a href="{% url 'purchase_app:add_to_cart' product_slug=product.product_slug %}"
                   class="py-3 px-4 bg-gray-800 rounded text-white flex gap-2 items-center justify-center w-full"
                   data-tootik="Add to Cart"><i class="fa fa-shopping-bag"></i><span class="">Add to Cart</span></a>
            </div>
        </div>
        <div class="related-product rounded-md border hidden lg:block w-full lg:w-1/5">
            <a href=""><img src="{% static 'home/images/banner1.png' %}" alt=""></a>
        </div>
    </div>
    <div class="flex gap-4 flex-col lg:flex-row flex-col-reverse">
        <div class="mt-4 border rounded-md details w-full lg:w-2/3 p-4">
            <h2 class="font-bold text-2xl">Product Details:</h2>
            {{ product.product_description|safe }}
        </div>
        <div class="mt-4 border rounded-md details w-full lg:w-1/3 p-4">

            {% if product.pk not in user_ratings %}
                <h2 class="font-bold text-2xl">Add a Review:</h2>
                <form action="" class="flex flex-col" method="POST">
                    {% csrf_token %}
                    <div class="flex gap-2">
                        <div class="star-widget pt-4">
                            <input type="radio" name="rating" id="rate_five" value="5" hidden>
                            <label for="rate_five"><i class="fa fa-star pl-2"></i></label>
                            <input type="radio" name="rating" id="rate_four" value="4" hidden>
                            <label for="rate_four"><i class="fa fa-star px-2"></i></label>
                            <input type="radio" name="rating" id="rate_three" value="3" hidden>
                            <label for="rate_three"><i class="fa fa-star px-2"></i></label>
                            <input type="radio" name="rating" id="rate_two" value="2" hidden>
                            <label for="rate_two"><i class="fa fa-star px-2"></i></label>
                            <input type="radio" name="rating" id="rate_one" value="1" hidden>
                            <label for="rate_one"><i class="fa fa-star pr-2"></i></label>
                        </div>
                    </div>
                    <label for="review" class="my-2 text-lg">Comment</label>
                    <textarea name="review" rows="5" class="border-2 resize-none p-4" id="review"></textarea>
                    <button type="submit"
                            class="bg-yellow-400 hover:bg-yellow-500 focus:bg-yellow-500 focus:outline-none py-1 px-2 my-2">
                        Submit
                    </button>
                </form>
            {% endif %}

            <h2 class="font-bold text-2xl my-2">All Reviews:</h2>
            {% for product_rating in product.product_ratings.all %}
                <div class="p-2 border rounded">
                    <h2 class="font-bold">{{ product_rating.user }}</h2>
                    <div class="flex gap-2 py-3 text-yellow-400">
                        {% for star in product_rating.product_rating|times %}
                            <i class="fa fa-star"></i>
                        {% endfor %}
                        {% for star in product_rating.product_rating|sub %}
                            <i class="fal fa-star"></i>
                        {% endfor %}


                    </div>
                    <p class="">{{ product_rating.product_comment }}</p>
                    <p class="text-gray-400 text-xs">{{ product_rating.rating_date }}</p>
                </div>
            {% endfor %}


        </div>
    </div>
{% endblock %}

{% block script_block %}
    <script>
        $(function () {

            $("#exzoom").exzoom({

                // thumbnail nav options
                "navWidth": 60,
                "navHeight": 60,
                "navItemNum": 5,
                "navItemMargin": 7,
                "navBorder": 1,

                // autoplay
                "autoPlay": true,

                // autoplay interval in milliseconds
                "autoPlayTimeout": 2000

            });

        });
    </script>
{% endblock %}

templates/home/profile-left-menu.html
<div class="flex flex-col gap-2 sticky top-20">
    <div class="border p-3 flex items-center">
        <div class="w-2/5"><img src="{{ user.user_profile.profile_pic.url }}" alt=""
                                class="w-10 h-10 object-cover rounded-full"></div>
        <div class="w-4/5 flex flex-col">
            <h2 class="font-semibold">{{ user.username }}</h2>
            {% for emailaddress in user.emailaddress_set.all %}
                {% if emailaddress.verified %}
                    <p class="bg-green-400 px-2 py-1 rounded-full text-white w-max">Verified</p>
                {% else %}
                    <p class="bg-red-400 px-2 py-1 rounded-full text-white w-max">UnVerified</p>
                {% endif %}
            {% endfor %}

        </div>
    </div>
    <div class="border p-3 flex gap-2 items-baseline">
        <i class="fal fa-address-card"></i>
        <div class="flex flex-col gap-1">
            <h2 class="font-semibold">Manage Account</h2>
            <a href="{% url 'profile_app:profile' %}" class="hover:text-yellow-500 transition duration-200">Profile Information</a>
            <a href="" class="hover:text-yellow-500 transition duration-200">Manage Address</a>
            <a href="{% url 'profile_app:change-password' %}" class="hover:text-yellow-500 transition duration-200">Change Password</a>
        </div>

    </div>
    <div class="border p-3 flex gap-2 items-baseline">
        <i class="fal fa-shopping-bag"></i>
        <div class="flex flex-col gap-1">
            <h2 class="font-semibold">Manage Orders</h2>
            <a href="" class="hover:text-yellow-500 transition duration-200">Order History</a>
            <a href="{% url 'profile_app:wish-list' %}" class="hover:text-yellow-500 transition duration-200">Wishlist</a>
            <a href="{% url 'profile_app:cart' %}" class="hover:text-yellow-500 transition duration-200">Cart</a>
        </div>

    </div>
    <div class="border p-3 flex gap-2 items-baseline">
        <i class="fal fa-money-bill"></i>
        <div class="flex flex-col gap-1">
            <h2 class="font-semibold">Manage Account</h2>
            <a href="" class="hover:text-yellow-500 transition duration-200">Payment Information</a>
        </div>

    </div>
</div>

templates/home/profile.html
{% extends 'home/base.html' %}
{% load static %}
{% block style_block %}

{% endblock %}
{% block body_block %}
    <div class="flex flex-col lg:flex-row gap-4">
        <div class="w-full lg:w-1/5">
            {% include 'home/profile-left-menu.html' %}
        </div>
        <div class="flex flex-col lg:flex-row gap-4 lg:w-4/5 w-full">
            <div class="flex gap-2 flex-col p-4 border rounded w-full lg:w-1/3" style="height: max-content">
                <div class="flex gap-6 justify-between">
                    <h2 class="font-bold">Personal Profile</h2>
                    <a href="{% url 'profile_app:edit-profile' %}" class="text-yellow-600">Edit</a>
                </div>
                <div class="">
                    <p class="font-bold">{{ user.user_profile.full_name }}</p>
                    <p>{{ user.user_profile.phone_one }}</p>
                    <p>{{ user.user_profile.phone_two }}</p>
                    <p>{{ user.email }}</p>
                </div>
            </div>
            <div class="flex gap-2 flex-col p-4 border rounded w-full lg:w-1/3" style="height: max-content">
                <div class="flex gap-6 justify-between">
                    <h2 class="font-bold">Billing Address</h2>
                    <a href="{% url 'profile_app:edit-billing-address' %}" class="text-yellow-600">Edit</a>
                </div>
                <div class="">
                    <p class="font-bold">{{ user.user_billing_address.name }}</p>
                    <p>{{ user.user_billing_address.get_full_address }}</p>
                    <p>{{ user.user_billing_address.phone }}</p>
                </div>
            </div>
            <div class="flex gap-2 flex-col p-4 border rounded w-full lg:w-1/3" style="height: max-content">
                <div class="flex gap-6 justify-between">
                    <h2 class="font-bold">Shipping Address</h2>
                    <a href="{% url 'profile_app:edit-shipping-address' %}" class="text-yellow-600">Edit</a>
                </div>
                <div class="">
                    <p class="font-bold">{{ user.user_shipping_address.name }}</p>
                    <p>{{ user.user_shipping_address.get_full_address }}</p>
                    <p>{{ user.user_shipping_address.phone }}</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block script_block %}

{% endblock %}

templates/home/registration.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load socialaccount %}
{% block style_block %}

{% endblock %}

{% block body_block %}

    <div class="p-10 border lg:mx-40">
        <div class="flex flex-col lg:flex-row text-center md:text-left pb-2 items-center justify-between">
            <h2 class="text-xl">Welcome, Please Register Here.</h2>
            <p class="">Already a Member? <a href="{% url 'profile_app:login' %}" class="text-blue-500">Login</a> Here.</p>
        </div>
        <div class="p-4">
            <form action="" class="flex flex-col items-center gap-8" method="POST">
                <div class="w-full">
                    {{ form|crispy }}
                    {% csrf_token %}
                </div>

                <div class="w-full flex flex-col gap-4 text-center">
                    <button type="submit"
                            class="bg-yellow-400 transition duration-300 hover:bg-yellow-500 focus:bg-yellow-500 text-white p-3 w-full">
                        Sign Up
                    </button>
                    <a href="{% provider_login_url "facebook" %}"
                       class="bg-blue-400 transition duration-300 hover:bg-blue-500 focus:bg-blue-500 text-white p-3 w-full">Facebook</a>
                    <a href="{% provider_login_url "google" %}"
                       class="bg-red-400 transition duration-300 hover:bg-red-500 focus:bg-red-500 text-white p-3 w-full">Google</a>
                </div>

            </form>
        </div>
    </div>
{% endblock %}

templates/home/wishlist.html
{% extends 'home/base.html' %}
{% load static %}
{% block style_block %}

{% endblock %}
{% block body_block %}
    <div class="flex gap-4">
        <div class="w-1/5 hidden lg:block">
            {% include 'home/profile-left-menu.html' %}

        </div>
        <div class="text-center lg:w-4/5 w-full">
            <div class="wishlist-head flex font-semibold text-md md:text-lg justify-between items-center">
                <div class="w-1/5 border">Image</div>
                <div class="w-1/5 border">Item</div>
                <div class="w-1/5 border">Price</div>
                <div class="w-1/5 border">Add to Cart</div>
                <div class="w-1/5 border">Remove</div>
            </div>
            {% for wishlist in wishlists %}
                {% if wishlist.product.product_quantity > 0 %}
                    <div class="wishlist-head flex justify-between items-center border">
                <div class="w-1/5 p-4 flex justify-center"><img src="{{ wishlist.product.image.url }}" alt=""
                                                                class="w-1/2"></div>
                <div class="w-1/5 p-4 ">
                    <div class="">
                        <a href="{% url 'product_details_app:product' product_slug=wishlist.product.product_slug %}"><h2 class="font-semibold">{{ wishlist.product.product_name }}</h2></a>
                        <p class="text-green-500">In Stock</p>
                    </div>
                </div>
                <div class="w-1/5 p-4 text-yellow-500 font-semibold">{{ wishlist.product.product_new_price }}</div>
                <div class="w-1/5 p-4"><a href=""
                                          class=""><span class="bg-yellow-400 hover:bg-yellow-500 focus:bg-yellow-500 focus:outline-none px-2 py-1 rounded hidden md:block">Add to Cart</span><span class="block md:hidden"><i class="fal fa-shopping-bag bg-yellow-400 focus:bg-yellow-500 hover:bg-yellow-500 focus:outline-none rounded p-2"></i></span></a></div>
                <div class="w-1/5 p-4"><a href="{% url 'product_details_app:remove_from_wishlist' id=wishlist.id %}" class="bg-red-400 hover:bg-red-500 focus:bg-red-500 focus:outline-none text-white px-2 py-1 rounded" data-tootik="Remove From Cart"><i class="fal fa-trash"></i></a></div>
            </div>
                    {% else %}
                    <div class="wishlist-head flex justify-between items-center border">
                <div class="w-1/5 p-4 flex justify-center"><img src="{{ wishlist.product.image.url }}" alt="" class="w-1/2"></div>
                <div class="w-1/5 p-4 ">
                    <div class="">
                        <h2 class="font-semibold">{{ wishlist.product.product_name }}</h2>
                        <p class="text-red-500">Out of Stock</p>
                    </div>
                </div>
                <div class="w-1/5 p-4 text-yellow-500 font-semibold">{{ wishlist.product.product_new_price }}</div>
                <div class="w-1/5 p-4"><span class="cursor-not-allowed bg-yellow-200 focus:outline-none px-2 py-1 rounded hidden md:block">Add to Cart</span><span class="block md:hidden"><i class="fal fa-shopping-bag cursor-not-allowed bg-yellow-200 focus:outline-none rounded p-2"></i></span></div>
                <div class="w-1/5 p-4"><a href="{% url 'product_details_app:remove_from_wishlist' id=wishlist.id %}" class="bg-red-400 hover:bg-red-500 focus:bg-red-500 focus:outline-none text-white px-2 py-1 rounded" data-tootik="Remove From Cart"><i class="fal fa-trash"></i></a></div>
            </div>
                {% endif %}
            {% endfor %}






        </div>
    </div>

{% endblock %}
{% block script_block %}

{% endblock %}