adminpanelapp/urls.py
from django.urls import path
from adminpanelapp import views

app_name = 'admin_app'

urlpatterns = [
    path('', views.adminindexview, name='adminindex'),
    path('all-user/', views.alluserview, name='all_user'),
    path('single-user/<str:user_pk>/', views.singleuserview, name='single_user'),
    path('single-user-edit/<str:user_pk>/', views.singleusereditview, name='single_user_edit'),
    path('order-details/', views.orderdetailsview, name='order_details'),
    path('order/', views.allorderview, name='order'),
    # Category URLS
    path('addcategories/', views.addcategoryview, name='add-categories'),
    path('valcategories/', views.validate_category, name='val-categories'),
    path('viewcategories/', views.viewcategoryview, name='view-categories'),
    path('deletecategories/<str:cat_pk>/', views.deletecategoryview, name='delete-categories'),
    path('editcategories/<str:cat_pk>/', views.editcategoryview, name='edit-categories'),

    path('addsubcategories/', views.addsubcategoryview, name='add-sub-categories'),
    path('viewsubcategories/', views.viewsubcategoryview, name='view-sub-categories'),
    path('deletesubcategories/<str:sub_cat_pk>/', views.deletesubcategoryview, name='delete-sub-categories'),
    path('editsubcategories/<str:sub_cat_pk>/', views.editsubcategoryview, name='edit-sub-categories'),

    path('addmanufacturer/', views.addmanufacturerview, name='add-manufacturer'),
    path('valmanufacturer/', views.validate_manufacturer, name='val-manufacturer'),
    path('viewmanufacturer/', views.viewmanufaturerview, name='view-manufacturer'),
    path('deletecompany/<str:man_pk>/', views.deletemanufacturerview, name='delete-company'),
    path('editcompany/<str:man_pk>/', views.editmanufacturerview, name='edit-company'),

    path('allproducts/', views.allproductsview, name='all-products'),
    path('subcategorydropdown/', views.load_subcategories, name='subcategory-dropdown'),
    path('addproducts/', views.addproductsview, name='add-products'),
    path('editproducts/<int:product_pk>', views.editproductsview, name='edit-products'),
    path('deleteproducts/<int:product_pk>', views.deleteproductsview, name='delete-products'),
    path('editproductsimages/<int:product_pk>', views.editproductsimageview, name='edit-products-images'),

    path('addcoupons/', views.addcouponview, name='add-coupons'),
    path('viewcoupons/', views.viewcouponview, name='view-coupons'),
    path('valcoupons/', views.validate_coupons, name='val-coupons'),
    path('deletecoupons/<str:coupon_pk>/', views.deletecouponsview, name='delete-coupons'),
    path('editcoupons/<str:coupon_pk>/', views.editcouponsview, name='edit-coupons'),

    path('adminlogin/', views.adminloginview, name='admin-login'),
    path('adminlogout/', views.adminlogoutview, name='admin-logout'),
]

apiapp/urls.py
from django.urls import path
from apiapp import views
app_name = 'api_app'
urlpatterns = [
    path('product/<product_slug>/', views.ProductApiView.as_view(), name='product'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('adminpanel/', include('adminpanelapp.urls')),
    path('', include('ecomapp.urls')),
    path('product/', include('productapp.urls')),
    path('purchase/', include('purchaseapp.urls')),
    path('account/', include('userapp.urls')),
    path('api/', include('apiapp.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/adminpanel/addsubcategory.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block style_block %}
    <style>
        .notfound {
            display: none;
        }
    </style>
{% endblock %}
{% block body_block %}
    <form action="" method="POST" id="add">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="mt-3 btn btn-primary">Add Sub-Category</button>
    </form>

    <div class="alert"></div>



    <form action="" method="GET" class="mt-3">
        <input type="search" class="form-control" placeholder="Search now" aria-label="search"
               aria-describedby="search" style="border-radius: 5px" id='txt_searchall' required>
    </form>

    <div class="bg-white mt-4 table-responsive" style="overflow: auto; height: 80vh;">
        <table id="myTable" class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>No</th>
                <th>Sub-Category Name</th>
                <th>Category ID</th>
                <th>Edit Name</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody id="empty">

            </tbody>
            <!-- Display this <tr> when no record found while search -->
            <tr class='notfound'>
                <td colspan="8">No record found</td>
            </tr>
        </table>
    </div>
{% endblock %}

{% block script_block %}
    <script>
        $(document).ready(function () {

            // Search all columns
            $('#txt_searchall').keyup(function () {
                // Search Text
                var search = $(this).val();

                // Hide all table tbody rows
                $('table tbody #search-tr').hide();

                // Count total search result
                var len = $('table tbody #search-tr:not(.notfound) td:contains("' + search + '")').length;

                if (len > 0) {
                    // Searching text in columns and show match row
                    $('table tbody #search-tr:not(.notfound) td:contains("' + search + '")').each(function () {
                        $(this).closest('#search-tr').show();
                        $('.notfound').hide();
                    });
                } else {
                    $('.notfound').show();
                }

            });

        });

        // Case-insensitive searching (Note - remove the below script for Case sensitive search )
        $.expr[":"].contains = $.expr.createPseudo(function (arg) {
            return function (elem) {
                return $(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
            };
        });
    </script>

    <script>
        // Showing Items in Table on page load from server
        $(document).ready(function () {
            $.ajax({
                type: 'GET',
                url: "{% url 'admin_app:view-sub-categories' %}",
                success: function (response) {

                    $('#empty').empty();
                    for (var key in response.data) {
                        let temp = `<tr id="search-tr"><th scope="row">${parseInt(key) + 1}</th><td>${response.data[key].subcategory_name}</td><td>${response.data[key].category_name_id}</td><td><a href="/adminpanel/editsubcategories/${response.data[key].id}" title="Edit" class="btn"><i class="mdi mdi-pencil-box"></i></a></td><td><a href="/adminpanel/deletesubcategories/${response.data[key].id}" class="btn" title="Delete" id="delete"><i class="mdi mdi-delete text-danger"></i></a></td></tr>`


                        $('#empty').append(temp);
                    }

                    // Using DataTableJS Plugin to make the table interactive
                    $('#myTable').DataTable({
                        "paging": true,
                        "ordering": true,
                        "info": true,
                        "searching": true
                    });

                },
                error: function (response) {
                    console.log('Nothing')
                }
            });

        })

        // Form Submitting without page loading
        $("#add").submit(function (e) {
            // prevent from normal form behaviour
            e.preventDefault();
            // serialize the form data
            var serializedData = $(this).serialize();
            $.ajax({
                type: 'POST',
                url: "{% url 'admin_app:add-sub-categories' %}",
                data: serializedData,
                success: function (response) {
                    //reset the form after successful submit
                    $("#add")[0].reset();

                    // Showing Item to the table after form submitting from server
                    $.ajax({
                        type: 'GET',
                        url: "{% url 'admin_app:view-sub-categories' %}",
                        success: function (response) {
                            $('#empty').empty();
                            for (var key in response.data) {
                                let temp = `<tr id="search-tr"><th scope="row">${parseInt(key) + 1}</th><td>${response.data[key].subcategory_name}</td><td>${response.data[key].category_name_id}</td><td><a href="/adminpanel/editsubcategories/${response.data[key].id}" title="Edit" class="btn"><i class="mdi mdi-pencil-box"></i></a></td><td><a href="/adminpanel/deletesubcategories/${response.data[key].id}" class="btn" title="Delete" id="delete"><i class="mdi mdi-delete text-danger"></i></a></td></tr>`

                                $('#empty').append(temp);

                                $('.alert').empty()
                                $('.alert').addClass('alert-success').append('Item Added Successfully')
                                setTimeout(function () {
                                    $('.alert').empty()
                                    $('.alert').removeClass('alert-success')
                                }, 1000)
                            }
                        },
                        error: function (response) {
                            console.log('Nothing')
                        }
                    });


                },
                error: function (response) {
                    console.log(response)
                }
            });

        });
    </script>
{% endblock %}

templates/adminpanel/adminlogin.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Majestic Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static "adminpanel/vendors/mdi/css/materialdesignicons.min.css" %}">
    <link rel="stylesheet" href="{% static "adminpanel/vendors/base/vendor.bundle.base.css" %}">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{% static "adminpanel/css/style.css" %}">
    <!-- endinject -->
    <link rel="shortcut icon" href="{% static "adminpanel/images/favicon.png" %}"/>
</head>

<body>
<div class="container-scroller">
    <div class="container-fluid page-body-wrapper full-page-wrapper">
        <div class="content-wrapper d-flex align-items-center auth px-0">
            <div class="row w-100 mx-0">
                <div class="col-lg-4 mx-auto">
                    <div class="auth-form-light text-left py-5 px-4 px-sm-5">
                        <div class="brand-logo">
                            <img src="{% static "adminpanel/images/logo.svg" %}" alt="logo">
                        </div>
                        <h4>Hello! let's get started</h4>
                        <h6 class="font-weight-light">Sign in to continue.</h6>
                        <form class="pt-3" method="POST">
                            {% if error_messages is not None %}
                            <div class="alert alert-block alert-danger">
                                <ul class="m-0">
                                    <li>{{ error_messages }}</li>
                                </ul>
                            </div>
                            {% endif %}

                            {{ form|crispy }}
                            {% csrf_token %}
                            <div class="mt-3">
                                <button type="submit"
                                        class="btn btn-block btn-primary btn-lg font-weight-medium auth-form-btn">SIGN
                                    IN
                                </button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- page-body-wrapper ends -->
</div>
<!-- container-scroller -->
<!-- plugins:js -->
<script src="{% static "adminpanel/vendors/base/vendor.bundle.base.js" %}"></script>
<!-- endinject -->
<!-- inject:js -->
<script src="{% static "adminpanel/js/off-canvas.js" %}"></script>
<script src="{% static "adminpanel/js/hoverable-collapse.js" %}"></script>
<script src="{% static "adminpanel/js/template.js" %}"></script>
<!-- endinject -->
</body>

</html>

templates/adminpanel/allproducts.html
{% extends 'adminpanel/base.html' %}
{% load static %}

{% block style_block %}
    <style>
        .notfound {
            display: none;
        }
    </style>
{% endblock %}
{% block body_block %}
    <div class="row">
        <div class="col">
            <a href="{% url "admin_app:add-products" %}" class="btn btn-primary">Add New Product</a>
        </div>

    </div>


    <form action="" method="GET" class="mt-3">
        <input type="search" class="form-control" placeholder="Search now" aria-label="search"
               aria-describedby="search" style="border-radius: 5px" id='txt_searchall' required>
    </form>

    <div class="bg-white mt-4 table-responsive" style="overflow: auto; height: 80vh;">
        <table id="myTable" class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>No</th>
                <th>Image</th>
                <th>Name</th>
                <th>Company Name</th>
                <th>Category Name</th>
                <th>Sub-Category Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Discount</th>
                <th>New Price</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            {% for product in products %}
                <tr id="search-tr">
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        {% for image in product_image %}
                            {% if image.product == product %}
                                <img src="{{ image.product_image.url }}" alt="">

                            {% endif %}
                        {% endfor %}
                    </td>
                    <td><a href="#">{{ product.product_name }}</a></td>
                    <td>{{ product.company_name }}</td>
                    <td>{{ product.category_name }}</td>
                    <td>{{ product.subcategory_name }}</td>
                    <td>{{ product.product_price }}</td>
                    <td>{{ product.product_quantity }}</td>
                    <td>{{ product.product_discount }}%</td>
                    <td>{{ product.product_new_price }}</td>
                    <td class="dots">
                        <i class="mdi mdi-dots-horizontal click" style="color: #007bff; cursor:pointer;"></i>
                        <div class="dot-menu">
                            <ul>
                                <li><a href="{% url "admin_app:edit-products" product_pk=product.pk %}">Edit</a></li>
                                <li><a href="{% url "admin_app:delete-products" product_pk=product.pk %}">Delete</a>
                                </li>
                            </ul>
                        </div>
                    </td>
                </tr>
            {% endfor %}


            </tbody>
            <!-- Display this <tr> when no record found while search -->
            <tr class='notfound'>
                <td colspan="8">No record found</td>
            </tr>
        </table>
    </div>
{% endblock %}

{% block script_block %}
    <script>
        $(document).ready(function () {

            // Search all columns
            $('#txt_searchall').keyup(function () {
                // Search Text
                var search = $(this).val();

                // Hide all table tbody rows
                $('table tbody #search-tr').hide();

                // Count total search result
                var len = $('table tbody #search-tr:not(.notfound) td:contains("' + search + '")').length;

                if (len > 0) {
                    // Searching text in columns and show match row
                    $('table tbody #search-tr:not(.notfound) td:contains("' + search + '")').each(function () {
                        $(this).closest('#search-tr').show();
                        $('.notfound').hide();
                    });
                } else {
                    $('.notfound').show();
                }

            });

        });

        // Case-insensitive searching (Note - remove the below script for Case sensitive search )
        $.expr[":"].contains = $.expr.createPseudo(function (arg) {
            return function (elem) {
                return $(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
            };
        });
    </script>
    <script>
        let dot = document.querySelectorAll('.click');
        let toggleMenu = document.querySelectorAll('.dot-menu')
        for (let i = 0; i < dot.length; i++) {
            dot[i].addEventListener('click', (e) => {
                toggleMenu[i].classList.toggle('visible')
            })
        }
    </script>
    <script>
        // Using DataTableJS Plugin to make the table interactive
        $('#myTable').DataTable({
            "paging": true,
            "ordering": true,
            "info": true,
            "searching": true
        });
    </script>
{% endblock %}

templates/adminpanel/editcoupons.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_block %}
    <form action="" method="POST" id="add" class="mx-5">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="mt-3 btn btn-primary">Edit Coupon</button>
    </form>

{% endblock %}

templates/adminpanel/editmanufacturer.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_block %}
    <form action="" method="POST" id="add" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="mt-3 btn btn-primary">Edit Company</button>
    </form>

{% endblock %}

templates/adminpanel/editsubcategory.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block body_block %}
    <form action="" method="POST" id="add">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="mt-3 btn btn-primary">Edit Sub-Category</button>
    </form>

{% endblock %}

templates/adminpanel/order.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% block style_block %}
    <style>
        .notfound {
            display: none;
        }
    </style>
{% endblock %}
{% block body_block %}
    <form action="" method="GET">
        <input type="search" class="form-control" placeholder="Search now" aria-label="search"
               aria-describedby="search" style="border-radius: 5px" id='txt_searchall' required>
    </form>

    <div class="row mt-3 bg-white p-4">
        <div class="col-md-12">
            <h2 class="display-4">All Orders:</h2>
        </div>
        <div class="table-responsive" style="overflow: auto; height: 100vh">
            <table id="recent-purchases-listing" class="table table-bordered table-hover table-striped">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Order ID</th>
                    <th>User Email</th>
                    <th>Date</th>
                    <th>Products</th>
                    <th>Total Price</th>
                    <th>Payment Status</th>
                    <th>Delivery Status</th>
                </tr>
                </thead>
                <tbody>
                <tr id="search-tr">
                    <th scope="row">1</th>
                    <td><a href="{% url "admin_app:order_details" %}">95623</a></td>
                    <td><a href="{% url "admin_app:single_user" %}">email@email.email</a></td>
                    <td>5 June 2020</td>
                    <td>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                    </td>
                    <td>50000</td>
                    <td><span class="badge badge-success" style="border-radius: 5px;">Paid</span></td>
                    <td><span class="badge badge-success" style="border-radius: 5px;">Delivered</span></td>
                </tr>
                <tr id="search-tr">
                    <th scope="row">1</th>
                    <td><a href="{% url "admin_app:order_details" %}">95623</a></td>
                    <td><a href="{% url "admin_app:single_user" %}">email@email.email</a></td>
                    <td>5 June 2020</td>
                    <td>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                    </td>
                    <td>50000</td>
                    <td><span class="badge badge-warning" style="border-radius: 5px;">UnPaid</span></td>
                    <td><span class="badge badge-info" style="border-radius: 5px;">Processing</span></td>
                </tr>
                <tr id="search-tr">
                    <th scope="row">1</th>
                    <td><a href="{% url "admin_app:order_details" %}">95623</a></td>
                    <td><a href="{% url "admin_app:single_user" %}">email@email.email</a></td>
                    <td>5 June 2020</td>
                    <td>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                    </td>
                    <td>50000</td>
                    <td><span class="badge badge-warning" style="border-radius: 5px;">UnPaid</span></td>
                    <td><span class="badge badge-warning" style="border-radius: 5px;">Cancelled</span></td>
                </tr>
                <tr id="search-tr">
                    <th scope="row">1</th>
                    <td><a href="{% url "admin_app:order_details" %}">95623</a></td>
                    <td><a href="{% url "admin_app:single_user" %}">email@email.email</a></td>
                    <td>5 June 2020</td>
                    <td>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                    </td>
                    <td>50000</td>
                    <td><span class="badge badge-danger" style="border-radius: 5px;">Failed</span></td>
                    <td><span class="badge badge-warning" style="border-radius: 5px;">Cancelled</span></td>
                </tr>
                <tr id="search-tr">
                    <th scope="row">1</th>
                    <td><a href="{% url "admin_app:order_details" %}">95623</a></td>
                    <td><a href="{% url "admin_app:single_user" %}">email@email.email</a></td>
                    <td>5 June 2020</td>
                    <td>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                    </td>
                    <td>50000</td>
                    <td><span class="badge badge-outline-danger" style="border-radius: 5px;">Refund Requested</span>
                    </td>
                    <td><span class="badge badge-outline-danger" style="border-radius: 5px;">Return Requested</span>
                    </td>
                </tr>
                <tr id="search-tr">
                    <th scope="row">1</th>
                    <td><a href="{% url "admin_app:order_details" %}">95623</a></td>
                    <td><a href="{% url "admin_app:single_user" %}">email@email.email</a></td>
                    <td>5 June 2020</td>
                    <td>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                    </td>
                    <td>50000</td>
                    <td><span class="badge badge-danger" style="border-radius: 5px;">Refunded</span></td>
                    <td><span class="badge badge-danger" style="border-radius: 5px;">Returned</span></td>
                </tr>
                <tr id="search-tr">
                    <th scope="row">1</th>
                    <td><a href="{% url "admin_app:order_details" %}">95623</a></td>
                    <td><a href="{% url "admin_app:single_user" %}">email@email.email</a></td>
                    <td>5 June 2020</td>
                    <td>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                        3 x laptop BDT-5000(BDT-500)<br>
                    </td>
                    <td>50000</td>
                    <td><span class="badge badge-success" style="border-radius: 5px;">Paid</span></td>
                    <td><span class="badge badge-info" style="border-radius: 5px;">Processing</span></td>
                </tr>

                </tbody>
                <!-- Display this <tr> when no record found while search -->
                <tr class='notfound'>
                    <td colspan="8">No record found</td>
                </tr>
            </table>
        </div>
    </div>
{% endblock %}

{% block script_block %}
    <script>
        $(document).ready(function () {

            // Search all columns
            $('#txt_searchall').keyup(function () {
                // Search Text
                var search = $(this).val();

                // Hide all table tbody rows
                $('table tbody #search-tr').hide();

                // Count total search result
                var len = $('table tbody #search-tr:not(.notfound) td:contains("' + search + '")').length;

                if (len > 0) {
                    // Searching text in columns and show match row
                    $('table tbody #search-tr:not(.notfound) td:contains("' + search + '")').each(function () {
                        $(this).closest('#search-tr').show();
                        $('.notfound').hide();
                    });
                } else {
                    $('.notfound').show();
                }

            });

        });

        // Case-insensitive searching (Note - remove the below script for Case sensitive search )
        $.expr[":"].contains = $.expr.createPseudo(function (arg) {
            return function (elem) {
                return $(elem).text().toUpperCase().indexOf(arg.toUpperCase()) >= 0;
            };
        });
    </script>
{% endblock %}

templates/adminpanel/product-add.html
{% extends 'adminpanel/base.html' %}
{% block body_block %}
    
{% endblock %}

templates/adminpanel/product-details.html
{% extends 'adminpanel/base.html' %}
{% block body_block %}
    
{% endblock %}

templates/adminpanel/subcategory_dropdown.html
<option value="">---------</option>
{% for subcategory in subcategories %}
<option value="{{ subcategory.pk }}">{{ subcategory.subcategory_name }}</option>
{% endfor %}

templates/adminpanel/user-single-edit.html
{% extends 'adminpanel/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block style_block %}

{% endblock %}
{% block body_block %}
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
{% endblock %}

{% block script_block %}

{% endblock %}